language: node_js

node_js:
  - stable

install: npm install

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE PropertyProLite;' -U postgres

script:
  - echo "test starts....."
  - npm run test

after_script:
  - npm install coveralls && npm run coverage
