language: node_js

node_js:
  - stable

install: npm install

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE Property-ProLite;' -U postgres
  - npm run testDb

script:
  - echo "test starts....."
  - npm run test

after_script:
  - npm install coveralls && npm run coverage
